export { default as Headline } from './Headline.svelte'
export { default as SubHeadline } from './SubHeadline.svelte'
export { default as CTASection } from './CTASection.svelte'
export { default as SocialProof } from './SocialProof.svelte'
export { default as MockupHand } from './MockupHand.png'
export { default as Mockup } from './MockUp.png'
